
name: Build PDF with LaTeX

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: tianon/latex
    steps:
      - uses: actions/checkout@v3
      - run: pandoc de_course_2025/*.md -o course_material.pdf --pdf-engine=xelatex -V mainfont="DejaVu Serif"
      - uses: actions/upload-artifact@v4
        with:
          name: course-pdf
          path: course_material.pdf
