name: Create PDF
on:
  push:
    paths:
      - 'de_course_2025/**'
jobs:
  create-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: de_course_2025/data_engineering_full_course.md
          output_dir: pdfs
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: course-pdfs
          path: pdfs
