name: Create PDF
on:
  push:
    paths:
      - 'de_course_2025/**'
jobs:
  create-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create PDF
        uses: docker://pandoc/latex:2.9
        with:
          args: --output=pdfs/course.pdf de_course_2025/data_engineering_full_course.md
      - uses: actions/upload-artifact@v3
        with:
          name: course-pdfs
          path: pdfs
